---
title: "House Price Prediction With Contributing Factors"
subtitle: "{{ CITY }} {{ CSA }}"
author: 
  name: "Carsten Lange"
  affiliation: "California State Polytechnic University, Pomona"
  email: CLange@cpp.edu
number-sections: true
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
    smart: false
    css: Results.css
execute:
  message: false
  warning: false
---



::: {.callout-note appearance="simple" icon=false}
<span style="font-size: 0.85em;">
**Disclaimer:** This is research in progress. Estimates are based on data from 2024 and are adjusted based on hte Case-Shiller-Index for Los Angeles County to reflect house price changes up to June 2026. The estimates give a guideline but they cannot provide precise predictions. Only houses below $3,000,000 were considered because higher priced houses crucially depend on individual properties Therefore, predictions for high priced houses are less reliable.The same is true for houses with a very low price. 
</span>
:::

## At a Glance

### House Price Prediction

Based on your chosen house size ({{ Bedrooms }} bedrooms and {{ Sqft | digit0_format }} Sqft ) and your chosen location  ({{ CITY }} {{ CSA }}) a machine learning algorithm ([**Gradient Boosting Trees**](https://ai.lange-analytics.com/htmlbook/TreeBased.html){target="_blank"})   was used to predict the house price. 

```{=html}
<table class="table table-bordered table-striped" style="max-width: 600px; margin: auto;">
  <thead>
    <tr>
      <th style="text-align: right;"><strong>Pred. Price: </strong></th>
      <th style="text-align: right;">{{ PredPrice | currency_format }}</th>
    </tr>
  </thead> 
</table>
```

### Contributing House Price Factors

A game theory based algorithm ([**SHAP**](https://ai.lange-analytics.com/htmlbook/Interpret.html#Interpret-Shap)) was used to calculate premiums and discounts to be paid for the presence or lack of certain amenities. 
Cumulatively, all premiums and discounts  explain the difference between an average house in Los Angeles County and the predicted house price.

```{=html}
<table class="table table-bordered table-striped" style="max-width: 600px; margin: auto;">
  <thead>
    <tr>
      <th style="text-align: right;"><strong>Avg. Price in LA County: </strong></th>
      <th style="text-align: right;">{{ SHAPBaseValue | currency_format }}</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td style="text-align: right;"><strong>Premium(+)<br>Discount(-)</strong></td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>House Scale/Layout</strong> (Bedrooms: {{ Bedrooms  | digit0_format }}, Sqft: {{ Sqft | digit0_format }})</td>
      <td style="text-align: right;">{{ SHAPPCA1PCA2 | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>Beach Drive Time</strong> ({{ BeachTime  | digit0_format }} Min.)</td>
      <td style="text-align: right;">{{ SHAPBeachTimeLN | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>School Quality Index</strong> ({{ ((SchoolQuality - 2407.7) / (2554.613 - 2407.7) * 100) | digit0_format }} in Neighborhood. LA County Avg.=100)</td>
      <td style="text-align: right;">{{ SHAPSchoolQuality | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>Median Income</strong> ({{ MedIncome  | currency_format }} in Neighborhood)</td>
      <td style="text-align: right;">{{ SHAPMedIncome | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>Restaurants per Square Mile</strong> ({{ RestaurantsPerSqMile  | digit2_format }} per Sq. Mile in Neighborhood)</td>
      <td style="text-align: right;">{{ SHAPRestaurantsPerSqMile | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>Crimes per Square Mile</strong> ({{ CrimesPerSqMile  | digit2_format }} per Sq. Mile in Neighborhood)</td>
      <td style="text-align: right;">{{ SHAPCrimesPerSqMile | currency_format }}</td>
    </tr>
    <tr>
      <td style="text-align: left;"><strong>Distance to the Closest Major Park</strong> ({{ (DistParksMeters * 0.000621371) | digit1_format }} miles)</td>
      <td style="text-align: right;">{{ SHAPDistParksMetersLN  | currency_format }}</td>
    </tr>
    <tr>
      <th style="text-align: right;"><strong>Predicted Price: </strong></th>
      <th style="text-align: right;">{{ PredPrice | currency_format }}</th>
    </tr>
    
  </tbody>
</table>
```




## Report for a {{ Bedrooms }} Bedroom House with {{ Sqft | digit0_format }} Sqft in {{ CITY }} {{ CSA }}

Below is detailed information about the central variables that contribute to the predicted housing price.

::::: {.callout-note collapse="true"}
### House Scale and Layout

**Selected House Properties:**\
Number of Bedrooms: {{ Bedrooms | digit0_format }}\
Sqft: {{ Sqft | digit0_format }}

**Average House in Los Angeles County:**\
Number of Bedrooms: {{ AvgBedrooms  | digit0_format }}\
Sqft:  {{ AvgSqft  | digit0_format }}

*Sqft* and the number of *Bedrooms* are closely correlated. Therefore, it is not possible to isolate each variable's influence on the housing price. To still consider both Bedrooms and Sqft they were transformed in two uncorrelated [**Principle Components**](https://aashu-aggarwal.medium.com/from-scattered-to-simple-how-pca-finds-order-in-data-chaos-d5d46e371a71){target="_blank"} . Cumulatively  *Sqft* and *Bedrooms* result in a\
**Total SHAP Premium(+)/ Discount (-):**  {{ SHAPPCA1PCA2 | currency_format }}

In many (but not all!) cases  the **first Principal Component's SHAP Value ({{ SHAPPCA1 | currency_format }} )** represents the premium(+)/discount(-)  for the **Scale** (the "bigness") of a house, while the **second Principal Component's SHAP Value ({{ SHAPPCA2 | currency_format }})** represents the premium(+)/discount(-) for the **Layout** (ratio between sqft and bedrooms) of a house.

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
An average sized house will result in small *SHAP* Premiums(+)/Discounts(-), but due to the non-linear nature of the [*Gradient Boosting Trees*](https://example.com){target="_blank"} algorithm, *SHAP* values will not be zero.
:::
::::
:::::

::::: {.callout-note collapse="true"}
### Drive Time to the Next Beach in Minutes and BeachTime SHAP Value

A network algorithm was used to calculate the drive time in normal traffic to the closest beach.

**Drive time from {{ CITY }} {{ CSA }} to the closest beach ({{ BeachName }}):**\
{{ BeachTime  | digit0_format }} Min.

**Average (geom.) drive time in Los Angeles County to the closest beach:**\
{{ GeoAvgBeachTime  | digit0_format }} Min.

**Resulting Beach Time SHAP Premium (+)/Discount(-):**\
{{ SHAPBeachTimeLN | currency_format }}

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
A house with a *Drive Time* to the next beach that equals the Los Angeles County average will have a small Beach Time *SHAP* Premium(+)/Discount(-). However, due to the non-linear nature of the [*Gradient Boosting Trees*](https://example.com){target="_blank"} algorithm, the *SHAP* value will not be zero.
:::
::::
:::::

::: {.callout-note collapse="true"}
### School Quality Index and Resulting SHAP Premium (+)/Discount(-)

School quality is expressed with an index. The index is 100 for the average school quality in Los Angeles County and 0 for the worst high school. 

**School Quality for the nearest high school from selected neighborhood in {{ CITY }} {{ CSA }}:**\
{{ ((SchoolQuality-2407.7)/(2555.681610302082-2407.7)*100) | digit1_format }}

**Average School Quality in Los Angeles County:**\
{{ ((AvgSchoolQuality-2407.7)/(2555.681610302082-2407.7)*100) | digit1_format }}


**Resulting SHAP Premium (+)/Discount (-):**\
{{ SHAPSchoolQuality | currency_format }}

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
A house with a *School Quality* that equals the average in Los Angeles County
will have a small *SHAP* Premium(+)/Discounts(-) but due to the non-linear nature
of the [*Gradient Boosting Trees*](https://example.com){target=
} algorithm,
the *SHAP* value will not be zero.
:::
::::


:::

::::: {.callout-note collapse="true"}
### Median Houshold Income


**Median Household Income in selected neighborhood in {{ CITY }} {{ CSA }}:**\
{{ MedIncome  | currency_format }}

**Average Median Household Income  in Los Angeles County:**\
{{ AvgMedIncome  | currency_format }}

**Resulting *Premium (+)*/*Discount (-)*:**\
{{ SHAPMedIncome | currency_format }}

The *Premium (+)*/*Discount (-)* does not only reflect the direct effect of median income on house prices. It also includes unobserved house and neighborhood properties that are correlated with income. Examples are the condition of a house and amenities in the neighborhood. Both increase with income.

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left: 3px solid #6c757d;"}
A house with a *Median Income* that equals the average in Los Angeles County will have a small *SHAP* Premium(+)/Discounts(-), but due to the non-linear nature of the [*Gradient Boosting Trees*](https://example.com){target="_blank"} algorithm, the *SHAP* value will not be zero.
:::
::::
:::::



::::: {.callout-note collapse="true"}
### Restaurants per Square Mile

The number of restaurants within a square mile serves as an indicator of a neighborhood's vibrancy and livelihood.

Using data from existing restaurants across Los Angeles County, we calculated density estimates for one-square-mile grid cells. Below is the restaurant density for the specific area surrounding the selected house location.

**Estimated Restaurants per Square Mile in selected neighborhood in {{ CITY }} {{ CSA }}:**\
{{ RestaurantsPerSqMile  | digit2_format }}

**Avg. Restaurants per Square Mile in Los Angeles County:**\
{{ AvgRestaurantsPerSqMile  | digit2_format }}

**Resulting *Premium (+)*/*Discount (-)*:**\
{{ SHAPRestaurantsPerSqMile | currency_format }}

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
A house with a *Restaurants per Square Mile* estimate that equals the average in Los Angeles County
will have a small *SHAP* Premium(+)/Discounts(-) but due to the non-linear nature
of the [*Gradient Boosting Trees*](https://example.com){target=
} algorithm,
the *SHAP* value will not be zero.
:::
::::

:::::

::::: {.callout-note collapse="true"}
### Crimes per Square Mile

Locations for crimes committed during the year 2024 in Los Angeles County were used to generate estimates for crime density for one square mile raster cells. The density for the raster cell the house is within is reported below.
Considered crimes include robbery, burglary, grand theft, and larceny theft.

**Crimes (2024) per Square Mile in selected neighborhood in {{ CITY }} {{ CSA }}:**\
{{ CrimesPerSqMile  | digit2_format }}

**Avg. Crimes  (2024) per Square Mile in Los Angeles County:**\
{{ AvgCrimesPerSqMile  | digit2_format }}

**Resulting *Premium (+)*/*Discount (-)*:**\
{{ SHAPCrimesPerSqMile | currency_format }}

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
A house with a *Crimes per Square Mile* estimate which equals the average in Los Angeles County
will have a small *SHAP* Premium(+)/Discounts(-) but due to the non-linear nature
of the [*Gradient Boosting Trees*](https://example.com){target=
} algorithm,
the *SHAP* value will not be zero.
:::
::::
:::::

::::: {.callout-note collapse="true"}
### Distance to the Closest Major Park 

For the selected house the distance to the closest major park was calculated. Parks considered as *major* must have at least an area of 1 square kilometer (0.4 square miles).

**Distance to the closest Major Park from {{ CITY }} {{ CSA }}:**\
{{ (DistParksMeters * 0.000621371) | digit1_format }} miles

**Avg. Distance to a Major Park in Los Angeles County::**\
{{ (AvgDistParksMeters  * 0.000621371) | digit1_format }} miles

**Resulting *Premium (+)*/*Discount (-)*:**\
{{ SHAPDistParksMetersLN  | currency_format }}

:::: {.small-note}
::: {.callout-note collapse="false" style="border-left-width: 3px;"}
A house with a *Distance to a Major Park* that equals the average in Los Angeles County
will have a small *SHAP* Premium(+)/Discounts(-) but due to the non-linear nature
of the [*Gradient Boosting Trees*](https://example.com){target=
} algorithm,
the *SHAP* value will not be zero.
:::
::::
:::::


 
## Acknowledgements

A big thank you to my students from EC 4448 Spatial Econometrics for supporting me with generating the spatial variables from various resources. Special thanks go to Bryan Campuzano-Serrano, Xavier Padilla, Donald Young.



